Code reformatting
Dar9586/NClientV2 pull request #265
Opened 2021-01-12 02:03 UTC by TacoTheDank

I did this because I find quite a lot of the code sorta hard to read through. Hopefully you're okay with this reformatting.

2021-01-12 09:06 UTC, Dar9586 commented on app/src/main/java/com/dar/nclientv2/GalleryActivity.java
>      public boolean onOptionsItemSelected(final MenuItem item) {
For the next Android updates using if instead of switch is required

2021-01-12 09:07 UTC, Dar9586 commented on app/src/main/java/com/dar/nclientv2/FavoriteActivity.java
> +        switch (item.getItemId()) {
For the next Android updates using if instead of switch is required

2021-01-12 09:08 UTC, Dar9586 commented on app/src/main/java/com/dar/nclientv2/HistoryActivity.java
> +        switch (item.getItemId()) {
For the next Android updates using if instead of switch is required

2021-01-12 09:09 UTC, Dar9586 commented on app/src/main/java/com/dar/nclientv2/LocalActivity.java
> +        switch (item.getItemId()) {
For the next Android updates using if instead of switch is required

2021-01-12 09:47 UTC, Dar9586 requested changes
Resource IDs will be non-final in Android Gradle Plugin version 5.0, so the switch statement can't be used anymore in these cases

2021-01-12 09:47 UTC, Dar9586 commented on app/src/main/java/com/dar/nclientv2/StatusViewerActivity.java
> +        switch (item.getItemId()) {
For the next Android updates using if instead of switch is required

2021-01-12 09:47 UTC, Dar9586 commented on app/src/main/java/com/dar/nclientv2/TagFilterActivity.java
> +        switch (id) {
For the next Android updates using if instead of switch is required

2021-01-12 09:47 UTC, Dar9586 commented on app/src/main/java/com/dar/nclientv2/ZoomActivity.java
> +        switch (id) {
For the next Android updates using if instead of switch is required

2021-01-12 09:47 UTC, Dar9586 commented on app/src/main/java/com/dar/nclientv2/SearchActivity.java
> +        switch (item.getItemId()) {
For the next Android updates using if instead of switch is required

2021-01-12 09:47 UTC, Dar9586 commented on app/src/main/java/com/dar/nclientv2/MainActivity.java
> +        switch (item.getItemId()) {
For the next Android updates using if instead of switch is required

2021-01-12 09:47 UTC, Dar9586 commented on app/src/main/java/com/dar/nclientv2/LocalActivity.java
> +        switch (item.getItemId()) {
For the next Android updates using if instead of switch is required

2021-01-12 09:47 UTC, Dar9586 commented on app/src/main/java/com/dar/nclientv2/HistoryActivity.java
> +        switch (item.getItemId()) {
For the next Android updates using if instead of switch is required

2021-01-12 09:47 UTC, Dar9586 commented on app/src/main/java/com/dar/nclientv2/FavoriteActivity.java
> +        switch (item.getItemId()) {
For the next Android updates using if instead of switch is required

2021-01-12 09:47 UTC, Dar9586 commented on app/src/main/java/com/dar/nclientv2/GalleryActivity.java
> +        switch (id) {
For the next Android updates using if instead of switch is required

2021-01-14 17:30 UTC, TacoTheDank commented
@Dar9586 Hmm, I'll see about those later.

2021-01-24 09:18 UTC, merged

2021-01-25 14:48 UTC, TacoTheDank commented
Thanks!